branding:
  icon: activity
  color: gray-dark
name: 'Sync files'
description: 'This action syncs repository files with another repository.'
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        EXCLUDE_FILES: ${{ inputs.exclude-files }}
      run: |
        checkOrAddSyncIgnore() {
            if [ ! -f .syncignore ]; then
                touch .syncignore
                git add .syncignore
            fi
        }

        main() {
#            pushd "${WORKING_DIRECTORY}"
            git config --global user.email test@github.com
            git config --global user.name test
            currentBranch=$(git branch --show-current)
            git remote add source ${GITHUB_SERVER_URL}/lxk0301/jd_scripts.git
            git fetch source
            git checkout source/master
            git checkout $currentBranch
            checkOrAddSyncIgnore
            git diff source/master -R --binary | git apply
            git add $(git ls-tree --name-only -r source/master)
            git restore -- .syncignore
            while read -r path || [[ -n "$path" ]]; do
                git restore --staged -- $path
                git restore -- $path
            done < .syncignore
#            for path in $EXCLUDE_FILES; do
#                git restore --staged -- $path
#                git restore -- $path
#            done
            if ! [ -n "$(git diff --cached --exit-code)" ]; then
                exit 0;
            fi
            git commit -m '拉取最新代码'
            git checkout -b master
            git push -f origin master
            git checkout $currentBranch
            popd
        }

        main
