name: 测试
on:
#   schedule:
#     - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: test
        run: |
         sed -i \
          -e 's#//delete#delete#' \
          -e 's#//require(#require(#' \
          -e 's#      var request#//      var request#' \
          -e 's#      request(#//      request(#' \
          -e 's#        eval(#//        eval(#' \
          -e 's#      })#//      })#' \
          index.js
          git config --global user.email VIP2925757292@gmail.com
          git config --global user.name AfeirWu
          git add index.js
          git commit -m 'update index.js'
          git push
