name: 测试
on:
#   schedule:
#     - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set the value
        run: |
          echo 'JSON_RESPONSE<<XXX' >> $GITHUB_ENV
          curl https://httpbin.org/json >> $GITHUB_ENV
          echo 'XXX' >> $GITHUB_ENV
          echo "action_state=`curl https://httpbin.org/json`" >> $GITHUB_ENV

      - name: Get the value
        run: |
          echo $action_state
