name: 测试
on:
#   schedule:
#     - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.PAT }}
      
      - name: checkout
        shell: bash
        run: |
          chmod +x main.sh
          main.sh
        env:
          SYNC_BRANCH_NAME: master
          SYNC_REPOSITORY: lxk0301/jd_scripts
          AUTHOR_EMAIL: action@github.com
          AUTHOR_NAME: AfeirWu
          EXCLUDE_FILES: /.github/workflows
          RESULT_BRANCH_NAME: main
