name: 测试
on:
#   schedule:
#     - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ env.PAT }}

      - name: Use local my-action
        uses: ./.github/actions/my-action
        with:
          git-author-email: 'AfeirWu@github.com'
          git-author-name: 'AfeirWu'
