name: 测试
on:
#   schedule:
#     - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v2
      
      - name: 修改文件信息
        run: |
          echo `git hash-object index.js`
          echo `cat index.js | base64 -w 0`
          sed -i \
          -e 's#//delete#delete#' \
          -e 's#//require(#require(#' \
          -e 's#      var request#//      var request#' \
          -e 's#      request(#//      request(#' \
          -e 's#        eval(#//        eval(#' \
          -e 's#      })#//      })#' \
          index.js
      
      - name: 提交修改文件
        run: |
          sha=`git hash-object index.js`
          base64Str=`cat index.js | base64 -w 0`
          echo $sha
          echo $base64Str
          curl \
            -X PUT \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ env.PAT }}" \
            -d '{"message":"修改index.js","content":"'$base64Str'","sha":"'$sha'"}' \
            https://api.github.com/repos/${{ github.repository }}/contents/index.js
