name: 测试
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        env: 
          ss: ${{toJSON(github.event)}}
        run: | 
          echo '${{env.ss}}'
          echo ${{github.event_name}}
          echo ${{github.event_path}}
