name: 测试
on:
#   schedule:
#     - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set the value
        run: |
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          curl https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/EsT8TdGSJd6io3WcOc7SNw==/ >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

