name: 测试
on:
#   schedule:
#     - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set the value
        run: |
          export res=`curl http://api.turinglabs.net/api/v1/jd/farm/create/111/ | grep -Po '[0-9]+'`
          echo 22222222
          echo $res

      - name: Get the value
        run: |
          echo $res
