name: 测试
on:
#   schedule:
#     - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set the value
        run: |
          code=0 
          while [$code==400] 
          do 
          code=$(curl http://api.turinglabs.net/api/v1/jd/farm/create/111/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]) 
          echo $code
          done
