name: 测试
on:
#   schedule:
#     - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set the value
        run: |
          export res=`curl http://api.turinglabs.net/api/v1/jd/farm/create/111/ | grep -Po '[0-9]+'`
          echo $res
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          curl http://api.turinglabs.net/api/v1/jd/farm/create/111/ | grep -Po '[0-9]+' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Get the value
        run: |
          echo $JSON_RESPONSE
